### ISSUE TITLE
Feature request: Option to add an invisible slope to the stairs.

### ISSUE THREAD

**Issue by sc0ttj** [GreatOdds/CSGStairs#2]
Firstly, great plugin! Thanks!

Can you please add a checkbox to the Inspector (right-hand menu) that, if ticked, also generates an invisible slope along the path, along with the stairs?

That would make the CSGStair nodes generated immediately usable by player controllers that have basic/naive stair handling (like mine!).

(I tried myself, and was hoping to have a PR, but I can't seem to get my head around it at all tbh!)

**Comment by GreatOdds** [comment]
The plugin currently uses a `CSGMesh3D` to show the mesh and provide collision (simply ticking `use_collision`).

To make the collision shape different from the visual, we would need to have a separate `StaticBody3D` with its own `CollisionShape3D` and a separate function to generate the collision shape.

**Comment by GreatOdds** [comment]
I have added an option for using slope collisions. This removes the vertices of the steps from the collision shape. Let me know if this is what you wanted.

**Comment by sc0ttj** [comment]
Works great, just what I was after :) 

I'd consider this issue closed.

Thanks very much for the speedy reply.
