### ISSUE TITLE
Blue lines when used with Decals

### ISSUE THREAD

**Issue by GonnaFlyMethod** [GreatOdds/CSGStairs#3]
Hey, I'm using this [version ](https://godotengine.org/asset-library/asset/2551)of the asset.  When the stairs are behind the decals there are some weird blue lines:

![image](https://github.com/user-attachments/assets/6e29f87d-ebd6-4916-b750-d6821398abd6)
Scene's set up:
![image](https://github.com/user-attachments/assets/02dad0d1-098b-4245-89ed-ceebf849ad35)

It's super visible when stairs doesn't have any materials assigned or there's a bright material. When I remove decals, the lines disappear.
It only happens with the CSG stairs.  Godot engine version: v4.2

**Comment by GreatOdds** [comment]
Could you send an example project where it happens?

The blue line looks similar to the gizmo for a decal. Does it disappear if you turn of decal gizmos in View > Gizmos?

**Comment by GreatOdds** [comment]
Do you have Debug > Visibile Collision Shapes turned on? It might be the collision shape that you are seeing.

![image](https://github.com/user-attachments/assets/69e4824f-a01b-4f60-a27c-208b3d3113a5)

**Comment by GonnaFlyMethod** [comment]
Hey, thanks for your answers, I would check this out today answers let you
know the result, if the lines still will be there I would assemble the
project for you

**Comment by GonnaFlyMethod** [comment]
Tried to turn off gizmos in View > Gizmos - still have these blue lines, Debug > Visible Collision Shapes is disabled. It's interesting, but my friends do not encounter such thing with stairs in their editors. But I do see the lines both in the editor and release build.

Let me prepare for you a godot project with decals and stairs set up

**Comment by GonnaFlyMethod** [comment]
Also, when the bottom of the stairs is generated I do not see those blue lines, only when placing decals under the stairs without generated bottom. Also, if the camera is under the stairs without bottom, and the decals is on the other side of the stairs, there are still those blue lines:
![image](https://github.com/user-attachments/assets/4fad1244-f1a6-4835-a845-aa06c4aafa3f)

Red color means that I do not generate bottom for the stairs, and the camera is placed in the volume that is kind of reserved for bottom of the stairs (this is the second case where I see the blue lines):
![image](https://github.com/user-attachments/assets/9407b185-9684-4b2d-8441-108c3c9113d0)

**Comment by GonnaFlyMethod** [comment]
Hi, here's the [project ](https://drive.google.com/file/d/1icXIQcu4yF2fayBOCO2mj_oUXiu2ow_A/view?usp=sharing)with reproduced issue. Godot version v4.2

I've spotted that it has something to do with lighting. The problem showed itself in runtime, when I've added `WorldEnvironment` to the nodes' hierarchy.

![image](https://github.com/user-attachments/assets/d2094989-2d19-4377-aa5b-f958d9d6002d)
![image](https://github.com/user-attachments/assets/0f46478f-da9c-4b7c-8b1f-bb9c0f986d91)

**Comment by GreatOdds** [comment]
I did some tests. It seems the lines show up for both the Stairs3D and the normal MeshInstance3D.

You can see the lines on the sphere mesh.
![OnSphere](https://github.com/user-attachments/assets/f5e4a0e8-3383-418a-a12c-74fc99dc5ac6)

This might be a bug with the Decals node and not related to Stairs3D. Could you also try the MeshInstance3D on your device?

**Comment by GreatOdds** [comment]
godotengine/godot#62073

Looks like there's already an issue for this. Do you also have an AMD GPU?

**Comment by GonnaFlyMethod** [comment]
Hello, thanks for investigation, yeah, I have AMD based graphics hardware, issue still persists on Godot 4.2, then. Do you have any ideas for workarounds?

**Comment by GonnaFlyMethod** [comment]
By the way, 2 of my friends that tested the scene both in the editor and in rutime, did not encounter such issues,  they are using NVIDIA

**Comment by GonnaFlyMethod** [comment]
I've tested decals with other meshes and here are results:
**1. Spheres:** 
I have weird lines with sphere mesh similar to your screenshots:
![image](https://github.com/user-attachments/assets/b3b4c64a-27af-4404-b5bd-6a831d1558ec)

**2. Capsules:**
Similar glitch with capsule mesh, but the artefacts appear at the top part of the capsule:
https://github.com/user-attachments/assets/d7d20866-1632-4608-ba4d-80c9949a9a75

**3. Cylinders:**
Similar glitch:
![image](https://github.com/user-attachments/assets/153cba7f-c358-45f1-94ad-ccf480283cd7)

**4. Prisms:**
Prisms are mostly ok, at least on my machine:
![image](https://github.com/user-attachments/assets/75b6c14b-89e4-427c-8b46-d3a539c4e7d8)

**5. Box meshes:**
Box meshes are ok as well:
![image](https://github.com/user-attachments/assets/16e133c6-23c4-4e54-bb4d-c5453b899180)

**6. Plane mesh:**
OK:
![image](https://github.com/user-attachments/assets/3d7974ec-03b4-4fd2-a41c-464a237f3923)

**7. Quad mesh**
OK:
![image](https://github.com/user-attachments/assets/215f098d-c3e9-4c5f-85a2-041255783cb7)

**8. Torus mesh**:
Not ok, the wireframe appears because of the decal node:
![image](https://github.com/user-attachments/assets/e70549c2-3c34-487f-bf41-c143a9ca1a78)

**9. Text mesh**
Not ok, the lines of wireframe appear:
![image](https://github.com/user-attachments/assets/32237066-91e9-4a54-87ae-a73031f164be)

**10. Tube trail mesh**
Not ok, the wireframe lines appear:
![image](https://github.com/user-attachments/assets/a6eedd22-de44-49db-85b1-7d5efdedd329)

**11.Ribbon trail mesh**
Not ok, lines still appear:
![image](https://github.com/user-attachments/assets/0abdbb12-61fd-4159-81b5-42628bd95e41)

**Comment by GreatOdds** [comment]
From what I read from the godot issue thread, it seems to be most noticeable on meshs with a high metallic and low roughness material.

As for workarounds, you could try the mobile renderer instead of forward+ (top right of the editor).
